{{- if .Values.oauthProxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server.fullname" . }}-authenticated-emails
data:
  authenticated-emails.txt: |
    # oAuth proxy additional allowed email addresses from google idp
{{ include "code-server.currentUser" . | indent 4 }}
{{- range .Values.oauthProxy.additionalAllowedEmails }}
{{ . | indent 4 }}
{{- end }}
{{- end }}
