{{- range .Values.deployments }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .namespace }}
  name: scaling-deploy-{{ .name }}
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - 'update'
  - 'get'
  - 'list'
  - 'patch'
{{- end }}
{{- range .Values.statefulsets }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .namespace }}
  name: scaling-sts-{{ .name }}
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - statefulsets
  - statefulsets/scale
  verbs:
  - 'update'
  - 'get'
  - 'list'
  - 'patch'
{{- end }}
