---
deployments: []
# - namespace: tooling
#   name: cluster-overprovisioner-jenkins-jobs
#   minReplicas: 0
#   maxReplicas: 2
#   scaleInSchedule: "0 18 * * 1-5"
#   scaleOutSchedule: "0 8 * * 1-5"

statefulsets: []
